version: "2"
services:
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
